export { default as ChatWindow } from './components/ChatWindow';
export { default as MessageBubble } from './components/MessageBubble';
export { default as InputArea } from './components/InputArea';
export { useChatActions } from './hooks/useChatActions';
export { useConversationActions } from './hooks/useConversationActions';
export { useAttachmentManager } from './hooks/useAttachmentManager';
export { useTauriEvents } from './hooks/useTauriEvents';
export { useChatInitialization } from './hooks/useChatInitialization';
export { useAutoTitle, triggerAutoTitle } from './hooks/useAutoTitle';
export { useConversationMessages } from './hooks/useConversationMessages';
export { isDefaultTitle, generateConversationTitle } from './utils/title-generator';
export { default as ChatFeature } from './feature.manifest';
