[[permission]]
identifier = "allow-ollama-commands"
description = "Enables interaction with the local Ollama node."
commands.allow = [
    "cmd_ollama_get_models",
    "cmd_ollama_chat",
    "cmd_ollama_pull_model",
    "cmd_ollama_abort_pull",
    "cmd_ollama_delete_model",
    "cmd_ollama_abort_chat",
    "cmd_ollama_check_health",
    "cmd_ollama_verify_service",
    "cmd_ollama_validate_model",
    "cmd_ollama_generate_title",
]
