//! AUTO-GENERATED by scripts/codegen-validation.mjs
//! Source of truth: packages/contracts/src/validation-limits.ts
//! DO NOT EDIT THIS FILE MANUALLY — changes will be overwritten.
//! Regenerate with: pnpm codegen:validation
//! Generated: 2026-08-13

// ====================== CHAT / OLLAMA LIMITS ======================

/// Maximum length for model / name strings (e.g. "llama3:latest").
pub const MAX_MODEL_NAME_LEN: usize = 128;

/// Maximum length for a request ID.
pub const MAX_REQUEST_ID_LEN: usize = 128;

/// Maximum length for a single message's content field (64 KiB).
pub const MAX_MESSAGE_CONTENT_LEN: usize = 65536;

/// Maximum number of messages in a single chat request.
pub const MAX_MESSAGES_COUNT: usize = 1000;

/// Maximum number of base64-encoded images per single message.
pub const MAX_IMAGES_PER_MESSAGE: usize = 10;

/// Maximum length for a single base64-encoded image string (10 MiB).
pub const MAX_IMAGE_B64_LEN: usize = 10485760;

/// Maximum length for a log entry string (10 KiB).
pub const MAX_LOG_ENTRY_LEN: usize = 10240;

/// Maximum length for a log-clear confirmation token (UUID v4 = 36 chars).
pub const MAX_LOG_CLEAR_TOKEN_LEN: usize = 64;

/// Maximum length for user/assistant message fragments sent to title generation (10 KiB).
pub const MAX_TITLE_INPUT_LEN: usize = 10240;

/// Maximum length for a role string.
pub const MAX_ROLE_LEN: usize = 32;

/// Maximum length for a feature name in structured logging.
pub const MAX_FEATURE_NAME_LEN: usize = 64;

/// Maximum length for an action name in structured logging.
pub const MAX_ACTION_NAME_LEN: usize = 128;

/// Maximum length for a trace context message.
pub const MAX_TRACE_MESSAGE_LEN: usize = 10240;

/// Maximum number of context fields in a trace entry.
pub const MAX_TRACE_CONTEXT_FIELDS: usize = 50;

/// Maximum length of a single context field value.
pub const MAX_TRACE_CONTEXT_VALUE_LEN: usize = 2048;

/// Allowed range for temperature: [min, max].
pub const TEMPERATURE_RANGE: (f32, f32) = (0.0, 2.0);

/// Allowed range for top_k: [min, max].
pub const TOP_K_RANGE: (u32, u32) = (1, 200);

/// Allowed range for top_p: [min, max].
pub const TOP_P_RANGE: (f32, f32) = (0.0, 1.0);

/// Allowed range for num_predict: [min, max]. `-1` is Ollama's sentinel for unlimited generation.
pub const NUM_PREDICT_RANGE: (i32, i32) = (-1, 32768);

/// Allowed range for num_ctx: [min, max]. 2M covers all current and near-future model context windows.
pub const NUM_CTX_RANGE: (u32, u32) = (1, 2097152);

/// Maximum number of stop sequences.
pub const MAX_STOP_SEQUENCES: usize = 10;

/// Maximum length of a single stop sequence string.
pub const MAX_STOP_SEQUENCE_LEN: usize = 256;

// ====================== ALLOWED VALUES ======================

/// Valid role strings accepted by the chat endpoint.
pub const VALID_ROLES: &[&str] = &["system", "user", "assistant"];

/// Valid language codes for title generation.
pub const VALID_LANGUAGES: &[&str] = &["en", "ar"];

// ====================== RAG LIMITS ======================

/// Maximum length for a RAG project name.
pub const MAX_PROJECT_NAME_LEN: usize = 256;

/// Maximum length for a RAG project path.
pub const MAX_PROJECT_PATH_LEN: usize = 4096;

/// Maximum number of ignore patterns per project.
pub const MAX_IGNORE_PATTERNS: usize = 100;

/// Maximum length of a single ignore pattern.
pub const MAX_IGNORE_PATTERN_LEN: usize = 512;

/// Maximum length for a RAG search query (10 KiB).
pub const MAX_SEARCH_QUERY_LEN: usize = 10240;

/// Maximum topK value for RAG search.
pub const MAX_TOP_K: usize = 50;

/// Minimum topK value for RAG search.
pub const MIN_TOP_K: usize = 1;

/// Maximum threshold value for RAG search.
pub const MAX_THRESHOLD: f32 = 1.0;

/// Minimum threshold value for RAG search.
pub const MIN_THRESHOLD: f32 = 0.0;

/// Maximum number of file chunks per query.
pub const MAX_FILE_CHUNKS_QUERY: usize = 100;

/// Maximum length for a file path in chunk queries.
pub const MAX_FILE_PATH_LEN: usize = 4096;

/// Default maximum character budget for assembled RAG context.
pub const MAX_RAG_CONTEXT_CHARS: usize = 20000;
